import {
  Activity,
  AlertCircle,
  AlertTriangle,
  ArrowDownRight,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  BarChart3,
  Bookmark,
  Calendar,
  CalendarCheck,
  CalendarDays,
  Camera,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ClipboardList,
  Clock,
  Cpu,
  Database,
  Download,
  Eye,
  EyeOff,
  FileSpreadsheet,
  Footprints,
  GitCompare,
  Image as ImageIcon,
  ImageOff,
  Info,
  LayoutGrid,
  List,
  ListChecks,
  Lock,
  LogIn,
  Map as MapIcon,
  MapPin,
  Package,
  PackageX,
  Plug,
  Plus,
  RefreshCw,
  Search,
  ShieldAlert,
  SlidersHorizontal,
  Smartphone,
  Star,
  Store,
  Swords,
  Target,
  TrendingDown,
  Upload,
  User,
  Users,
  X,
  type LucideProps,
} from "lucide-react";

/**
 * The designs referenced icons by lucide's kebab-case names (`data-lucide="…"`).
 * Keeping that vocabulary means the components read like the source, and this
 * registry stays the single place to touch if lucide renames an icon.
 */
const ICONS = {
  activity: Activity,
  'alert-circle': AlertCircle,
  'alert-triangle': AlertTriangle,
  'arrow-down-right': ArrowDownRight,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-up-right': ArrowUpRight,
  'bar-chart-3': BarChart3,
  bookmark: Bookmark,
  calendar: Calendar,
  'calendar-check': CalendarCheck,
  'calendar-days': CalendarDays,
  camera: Camera,
  check: Check,
  'check-circle-2': CheckCircle2,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  'clipboard-list': ClipboardList,
  clock: Clock,
  cpu: Cpu,
  database: Database,
  download: Download,
  eye: Eye,
  'eye-off': EyeOff,
  'file-spreadsheet': FileSpreadsheet,
  footprints: Footprints,
  'git-compare': GitCompare,
  image: ImageIcon,
  'image-off': ImageOff,
  info: Info,
  'layout-grid': LayoutGrid,
  list: List,
  'list-checks': ListChecks,
  lock: Lock,
  'log-in': LogIn,
  map: MapIcon,
  'map-pin': MapPin,
  package: Package,
  'package-x': PackageX,
  plug: Plug,
  plus: Plus,
  'refresh-cw': RefreshCw,
  search: Search,
  'shield-alert': ShieldAlert,
  'sliders-horizontal': SlidersHorizontal,
  smartphone: Smartphone,
  star: Star,
  store: Store,
  swords: Swords,
  target: Target,
  'trending-down': TrendingDown,
  upload: Upload,
  user: User,
  users: Users,
  x: X,
} as const;

export type IconName = keyof typeof ICONS;

type IconProps = Omit<LucideProps, "ref"> & {
  name: IconName;
  /** Square size in px. The designs ran lucide at 18 by default. */
  size?: number;
};

export function Icon({ name, size = 18, ...props }: IconProps) {
  const Glyph = ICONS[name];
  return <Glyph width={size} height={size} strokeWidth={1.5} {...props} />;
}
